---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.42.12.1
        peer-asn: 65001
        my-asn: 65001
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.42.0.0/24